// video_video_pll_0.v

// This file was auto-generated from altera_up_avalon_video_pll_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.0 614

`timescale 1 ps / 1 ps
module video_video_pll_0 (
		input  wire  ref_clk_clk,        //      ref_clk.clk
		input  wire  ref_reset_reset,    //    ref_reset.reset
		output wire  video_in_clk_clk,   // video_in_clk.clk
		output wire  lcd_clk_clk,        //      lcd_clk.clk
		output wire  reset_source_reset  // reset_source.reset
	);

	wire    video_pll_locked_export; // video_pll:locked -> reset_from_locked:locked

	video_video_pll_0_video_pll video_pll (
		.refclk   (ref_clk_clk),             //  refclk.clk
		.rst      (ref_reset_reset),         //   reset.reset
		.outclk_0 (video_in_clk_clk),        // outclk0.clk
		.outclk_1 (),                        // outclk1.clk
		.outclk_2 (lcd_clk_clk),             // outclk2.clk
		.locked   (video_pll_locked_export)  //  locked.export
	);

	altera_up_avalon_reset_from_locked_signal reset_from_locked (
		.reset  (reset_source_reset),      // reset_source.reset
		.locked (video_pll_locked_export)  //       locked.export
	);

endmodule
